"""empty message

Revision ID: 3f2055240bd4
Revises: cd4553e1fd66
Create Date: 2020-05-11 10:24:25.702837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2055240bd4'
down_revision = 'cd4553e1fd66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.add_column('blogposts', sa.Column('category', sa.String(length=200), nullable=False))
    op.drop_constraint('blogposts_category_id_fkey', 'blogposts', type_='foreignkey')
    op.drop_column('blogposts', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('blogposts_category_id_fkey', 'blogposts', 'categories', ['category_id'], ['id'])
    op.drop_column('blogposts', 'category')
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    # ### end Alembic commands ###
