"""empty message

Revision ID: 4fc42584b5ca
Revises: 471ff5673ce2
Create Date: 2020-05-09 21:40:37.302832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc42584b5ca'
down_revision = '471ff5673ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('image_file', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogposts', 'image_file')
    # ### end Alembic commands ###
