"""empty message

Revision ID: 54ceadb413ae
Revises: 3f2055240bd4
Create Date: 2020-05-11 10:25:49.812360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ceadb413ae'
down_revision = '3f2055240bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('category', sa.String(length=200), nullable=False))
    op.drop_column('blogposts', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('blogposts', 'category')
    # ### end Alembic commands ###
