"""second migration after creation of a one-to-many relationship between the user and role class

Revision ID: 554e3c667410
Revises: 318d8335081c
Create Date: 2020-05-08 23:40:09.185141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554e3c667410'
down_revision = '318d8335081c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
