"""empty message

Revision ID: 72ba3099f208
Revises: c137fbb05504
Create Date: 2020-05-09 21:39:14.093864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ba3099f208'
down_revision = 'c137fbb05504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('image_file', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogposts', 'image_file')
    # ### end Alembic commands ###
