"""empty message

Revision ID: cd4553e1fd66
Revises: 4fc42584b5ca
Create Date: 2020-05-11 09:31:05.263181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4553e1fd66'
down_revision = '4fc42584b5ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_title', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blogposts', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'blogposts', 'categories', ['category_id'], ['id'])
    op.drop_column('blogposts', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('category', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'blogposts', type_='foreignkey')
    op.drop_column('blogposts', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
